### ISSUE TITLE
Resource Packs

### ISSUE THREAD

**Issue by steviegt6** [Steviegt6/BasicClicker#5]
Implement resource packs with dynamic image sizing, along with swapping out music files (and later fonts, etc.) as well.
Similar to how Minecraft's resource packs (_not_ texture packs) work.
A good example of what not to do is Terraria's texture packs.

**Comment by Mellozx** [comment]
So mods? lol? or just a basic interface for easy swapping out meshes and stuff?

**Comment by steviegt6** [comment]
> 
> 
> So mods? lol? or just a basic interface for easy swapping out meshes and stuff?

Don't know how else you can interpret "texture packs" when we already have mods planned separately.

**Comment by Mellozx** [comment]
Well I already got the idea of what this is, you kinda responded very late 😔 but yeah I get it now
